#!/usr/bin/env python3
"""
Build the STUDENT EDITION of the course site into docs/.

Why this exists
---------------
reveal.js keeps speaker notes in the HTML and lets ANY viewer press "S" to open
the speaker view. Publishing the authoring file directly would hand students:
  - every speaker note
  - the easter-egg answer
  - the Human-or-AI answer key
  - the live-session mechanics they don't need for self-study

So we publish a stripped copy instead. The authoring files in weeks/ stay intact
for you; docs/ is what GitHub Pages serves.

What gets removed
-----------------
  1. every <aside class="notes">...</aside>
  2. the notes plugin (so pressing S does nothing)
  3. any <section data-instructor>...</section>  (live-only slides)

Usage
-----
    python3 build.py            # build, then verify
    python3 build.py --check    # verify only, don't write

Then point GitHub Pages at:  Settings -> Pages -> Branch: main, Folder: /docs
"""

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "docs"

# Copied verbatim into docs/ — NOT stripped.
#
# "intro" is the instructor-introduction deck, presented by a colleague who needs its
# speaker notes to read the script. It is published WITH notes on purpose. Its notes
# contain no answer keys and no student names; the leak check below still enforces that.
COPY_DIRS = ["assets", "intro"]
COPY_FILES = ["index.html", ".nojekyll"]

# Which weeks students may see. Bump this the day you teach the week.
# A deck that exists in weeks/ but is not listed here stays unpublished, so
# next week's draft can live in the repo without leaking early.
RELEASED_WEEKS = {1}

# Never publish these, whatever happens
NEVER_PUBLISH = {"instructor", "exercises", ".git", "docs", "__pycache__"}

# Strings that must NOT appear anywhere in the built output.
# Add a student's name here and the build will fail if it ever leaks.
#
# NOTE: the easter-egg ANSWER ("Attention Is All You Need") is deliberately NOT
# forbidden — the whole game is that the answer is findable in the week's material.
# What must not leak is the instructor note that hands it over, and the answer keys.
FORBIDDEN = [
    'aside class="notes"',
    "Answer (do not say it)",
    "ANSWERS:",
    "ANSWER KEY",
    "instructor answer key",
]

# Real student names live in instructor/forbidden-names.txt, which is gitignored.
# Keeping them out of this file means build.py itself is safe to publish.
_NAMES = ROOT / "instructor" / "forbidden-names.txt"
if _NAMES.exists():
    FORBIDDEN += [
        line.strip() for line in _NAMES.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]


def _drop_instructor_sections(html: str) -> str:
    """
    Remove every <section ... data-instructor ...> ... </section>.

    Sections nest (reveal.js vertical stacks are a <section> of <section>s), so a
    non-greedy regex would stop at the first inner </section> and leave orphan
    tags behind. This walks the tags and matches them properly.
    """
    tag = re.compile(r"</?section\b[^>]*>", re.I)
    spans = []          # (start, end) of whole instructor sections
    stack = []          # (depth_index, is_instructor, start_offset)
    depth = 0
    target_depth = None
    start = None

    for m in tag.finditer(html):
        text = m.group(0)
        closing = text.startswith("</")
        if not closing:
            if target_depth is None and "data-instructor" in text:
                target_depth = depth
                start = m.start()
            depth += 1
        else:
            depth -= 1
            if target_depth is not None and depth == target_depth:
                spans.append((start, m.end()))
                target_depth = None
                start = None

    # cut from the end so earlier offsets stay valid
    for s, e in reversed(spans):
        line_start = html.rfind("\n", 0, s) + 1
        trailing = e
        while trailing < len(html) and html[trailing] in " \t":
            trailing += 1
        if trailing < len(html) and html[trailing] == "\n":
            trailing += 1
        html = html[:line_start] + html[trailing:]

    return html


def strip_deck(html: str) -> str:
    """Remove speaker notes, the notes plugin, and instructor-only slides."""
    # 1. instructor-only slides (do this first: they contain notes too)
    html = _drop_instructor_sections(html)
    # 2. speaker notes
    html = re.sub(
        r'[ \t]*<aside class="notes">.*?</aside>\s*\n?',
        "", html, flags=re.S,
    )
    # 3. notes plugin script tag + its registration
    html = re.sub(r'[ \t]*<script src="[^"]*plugin/notes\.js"></script>\s*\n', "", html)
    html = re.sub(r",?\s*plugins:\s*\[\s*RevealNotes\s*\]", "", html)
    # 4. a visible marker so you can tell the two editions apart
    html = html.replace(
        "<body>",
        "<body>\n<!-- STUDENT EDITION - generated by build.py, do not edit by hand -->",
        1,
    )
    return html


def build() -> list[Path]:
    # Wipe and rebuild when we can. Some environments (mounted folders, locked
    # files) refuse unlink; in that case fall back to overwriting in place.
    if OUT.exists():
        try:
            shutil.rmtree(OUT)
        except OSError as exc:
            print(f"  note: could not wipe docs/ ({exc.strerror}) — overwriting in place")
    OUT.mkdir(parents=True, exist_ok=True)

    written = []

    for d in COPY_DIRS:
        src = ROOT / d
        if src.exists():
            shutil.copytree(src, OUT / d, dirs_exist_ok=True)
            written.append(OUT / d)

    for f in COPY_FILES:
        src = ROOT / f
        if src.exists():
            shutil.copy2(src, OUT / f)
            written.append(OUT / f)
    (OUT / ".nojekyll").touch()

    weeks_src = ROOT / "weeks"
    if weeks_src.exists():
        for deck in sorted(weeks_src.glob("week*/index.html")):
            n = int(re.sub(r"\D", "", deck.parent.name) or 0)
            if n not in RELEASED_WEEKS:
                print(f"  weeks/{deck.parent.name}  ->  SKIPPED (not in RELEASED_WEEKS)")
                continue
            rel = deck.relative_to(ROOT)
            dest = OUT / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            original = deck.read_text(encoding="utf-8")
            stripped = strip_deck(original)
            dest.write_text(stripped, encoding="utf-8")
            removed = original.count('<aside class="notes">')
            saved = len(original) - len(stripped)
            print(f"  {rel}  ->  docs/{rel}   ({removed} notes removed, {saved:,} chars)")
            written.append(dest)

    return written


def check() -> bool:
    """Fail loudly if anything secret made it into docs/."""
    ok = True
    if not OUT.exists():
        print("docs/ does not exist — run the build first.")
        return False

    for path in sorted(OUT.rglob("*")):
        if not path.is_file():
            continue
        rel_parts = path.relative_to(OUT).parts
        if any(part in NEVER_PUBLISH for part in rel_parts):
            print(f"  LEAK: docs/{'/'.join(rel_parts)} should never be published")
            ok = False
        if path.suffix.lower() not in {".html", ".md", ".css", ".js", ".svg", ".txt"}:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if "reveal/dist" in str(path):      # vendored library, not ours
            continue

        # The intro deck is published with its speaker notes on purpose (see COPY_DIRS).
        # Every OTHER forbidden string — answer keys, student names — is still checked here,
        # so this exception is exactly one string wide and applies to exactly one folder.
        needles = FORBIDDEN
        if rel_parts and rel_parts[0] == "intro":
            needles = [n for n in FORBIDDEN if n != 'aside class="notes"']

        for needle in needles:
            if needle in text:
                print(f"  LEAK: '{needle}' found in {path.relative_to(ROOT)}")
                ok = False

    for folder in NEVER_PUBLISH:
        if (OUT / folder).exists():
            print(f"  LEAK: docs/{folder}/ exists")
            ok = False

    return ok


if __name__ == "__main__":
    check_only = "--check" in sys.argv

    if not check_only:
        print("Building student edition into docs/ …")
        build()

    print("\nChecking for leaks …")
    if check():
        print("  clean — no notes, no answer keys, no student names.")
        print("\nPublish with:")
        print("  git add -A && git commit -m 'Publish week' && git push")
        print("Pages setting:  Branch: main   Folder: /docs")
    else:
        print("\nBUILD IS NOT SAFE TO PUBLISH — fix the leaks above.")
        sys.exit(1)
